/**
 * BrainRAY_Continuation_v6.0_modular
 * Source behavior: BrainRAY_Continuation_v5.1
 *
 * All environment variables and default thresholds.
 */

import { n, s, b, normalizeSymbol, safeJsonParse } from "./utils.js";

export const CONFIG = {
  PORT: n(process.env.PORT, 8080),
  DEBUG: b(process.env.DEBUG, true),
  BRAIN_NAME: s(process.env.BRAIN_NAME, "BrainRAY_Continuation_v5.1"),

  WEBHOOK_SECRET: s(process.env.WEBHOOK_SECRET, ""),
  TICKROUTER_SECRET: s(process.env.TICKROUTER_SECRET, ""),
  WEBHOOK_PATH: s(process.env.WEBHOOK_PATH, "/webhook"),

  SYMBOL: normalizeSymbol(s(process.env.SYMBOL || "BINANCE:SOLUSDT")),
  ENTRY_TF: s(process.env.ENTRY_TF || "5"),
  TICK_MAX_AGE_SEC: n(process.env.TICK_MAX_AGE_SEC, 60),
  FEATURE_MAX_AGE_SEC: n(process.env.FEATURE_MAX_AGE_SEC, 900),
  REPLAY_ALLOW_STALE_DATA: b(process.env.REPLAY_ALLOW_STALE_DATA, false),
  REPLAY_USE_EVENT_TIME_FOR_POSITION_CLOCK: b(
    process.env.REPLAY_USE_EVENT_TIME_FOR_POSITION_CLOCK,
    true
  ),

  ENTER_DEDUP_MS: n(process.env.ENTER_DEDUP_MS, 90000),
  EXIT_DEDUP_MS: n(process.env.EXIT_DEDUP_MS, 60000),
  EXIT_COOLDOWN_MIN: n(process.env.EXIT_COOLDOWN_MIN, 12),
  REENTRY_ENTER_DEDUP_MS: n(process.env.REENTRY_ENTER_DEDUP_MS, 8000),

  C3_SIGNAL_URL: s(process.env.C3_SIGNAL_URL || process.env.THREECOMMAS_WEBHOOK_URL, ""),
  C3_SIGNAL_SECRET: s(process.env.C3_SIGNAL_SECRET || process.env.THREECOMMAS_SECRET, ""),
  C3_TIMEOUT_MS: n(process.env.C3_TIMEOUT_MS || process.env.THREECOMMAS_TIMEOUT_MS, 8000),
  MAX_LAG_SEC: n(process.env.MAX_LAG_SEC || process.env.THREECOMMAS_MAX_LAG, 300),
  SYMBOL_BOT_MAP: safeJsonParse(process.env.SYMBOL_BOT_MAP || "{}", {}),
  ENABLE_HTTP_FORWARD: b(process.env.ENABLE_HTTP_FORWARD, true),

  RAY_USE_BULLISH_TREND_CHANGE: b(process.env.RAY_USE_BULLISH_TREND_CHANGE, true),
  RAY_USE_BULLISH_TREND_CONTINUATION: b(process.env.RAY_USE_BULLISH_TREND_CONTINUATION, true),
  RAY_USE_BULLISH_BOS: b(process.env.RAY_USE_BULLISH_BOS, true),
  RAY_USE_BEARISH_TREND_CHANGE: b(process.env.RAY_USE_BEARISH_TREND_CHANGE, true),
  RAY_USE_BEARISH_TREND_CONTINUATION: b(process.env.RAY_USE_BEARISH_TREND_CONTINUATION, true),

  RAY_CONFLICT_GUARD_ENABLED: b(process.env.RAY_CONFLICT_GUARD_ENABLED, true),
  RAY_CONFLICT_GUARD_SEC: n(process.env.RAY_CONFLICT_GUARD_SEC, 45),
  RAY_CONFLICT_CONFIRM_FEATURE_BARS: n(process.env.RAY_CONFLICT_CONFIRM_FEATURE_BARS, 1),
  RAY_CONFLICT_KEEP_CURRENT_REGIME_IF_UNCLEAR: b(
    process.env.RAY_CONFLICT_KEEP_CURRENT_REGIME_IF_UNCLEAR,
    true
  ),
  RAY_CONFLICT_REQUIRE_CLOSE_CONFIRM_OVER_EMA18: b(
    process.env.RAY_CONFLICT_REQUIRE_CLOSE_CONFIRM_OVER_EMA18,
    true
  ),

  REQUIRE_EMA8_ABOVE_EMA18: b(process.env.REQUIRE_EMA8_ABOVE_EMA18, true),
  REQUIRE_CLOSE_ABOVE_EMA8: b(process.env.REQUIRE_CLOSE_ABOVE_EMA8, true),
  MIN_RSI_LONG: n(process.env.MIN_RSI_LONG, 48),
  MIN_ADX_CONTINUATION: n(process.env.MIN_ADX_CONTINUATION, 14),
  CONTINUATION_MAX_CHASE_PCT: n(process.env.CONTINUATION_MAX_CHASE_PCT, 0.35),
  MAX_EXT_FROM_EMA8_PCT: n(process.env.MAX_EXT_FROM_EMA8_PCT, 0.75),
  MAX_EXT_FROM_EMA18_PCT: n(process.env.MAX_EXT_FROM_EMA18_PCT, 1.2),

  // v5.0 first Bullish Trend Change entry engine
  FIRST_ENTRY_ENGINE_ENABLED: b(process.env.FIRST_ENTRY_ENGINE_ENABLED, true),
  FIRST_ENTRY_IMMEDIATE_MIN_RSI: n(process.env.FIRST_ENTRY_IMMEDIATE_MIN_RSI, 55),
  FIRST_ENTRY_IMMEDIATE_MIN_ADX: n(process.env.FIRST_ENTRY_IMMEDIATE_MIN_ADX, 14),
  FIRST_ENTRY_IMMEDIATE_MAX_CHASE_PCT: n(process.env.FIRST_ENTRY_IMMEDIATE_MAX_CHASE_PCT, 0.35),
  FIRST_ENTRY_IMMEDIATE_MAX_EXT_EMA18_PCT: n(process.env.FIRST_ENTRY_IMMEDIATE_MAX_EXT_EMA18_PCT, 1.20),
  FIRST_ENTRY_REQUIRE_EMA8_ABOVE_EMA18: b(process.env.FIRST_ENTRY_REQUIRE_EMA8_ABOVE_EMA18, true),
  FIRST_ENTRY_REQUIRE_CLOSE_ABOVE_EMA8: b(process.env.FIRST_ENTRY_REQUIRE_CLOSE_ABOVE_EMA8, true),
  FIRST_ENTRY_CONFIRM_ENABLED: b(process.env.FIRST_ENTRY_CONFIRM_ENABLED, true),
  FIRST_ENTRY_CONFIRM_WINDOW_SEC: n(process.env.FIRST_ENTRY_CONFIRM_WINDOW_SEC, 45),
  FIRST_ENTRY_CONFIRM_MIN_RSI: n(process.env.FIRST_ENTRY_CONFIRM_MIN_RSI, 52),
  FIRST_ENTRY_CONFIRM_MIN_ADX: n(process.env.FIRST_ENTRY_CONFIRM_MIN_ADX, 12),
  FIRST_ENTRY_CONFIRM_MAX_CHASE_PCT: n(process.env.FIRST_ENTRY_CONFIRM_MAX_CHASE_PCT, 0.38),
  FIRST_ENTRY_CONFIRM_TICK_CONFIRM_PCT: n(process.env.FIRST_ENTRY_CONFIRM_TICK_CONFIRM_PCT, 0.05),
  FIRST_ENTRY_CONFIRM_MIN_TICKS: n(process.env.FIRST_ENTRY_CONFIRM_MIN_TICKS, 2),
  FIRST_ENTRY_CONFIRM_ALLOW_CLOSE_NEAR_EMA8: b(process.env.FIRST_ENTRY_CONFIRM_ALLOW_CLOSE_NEAR_EMA8, true),
  FIRST_ENTRY_CONFIRM_MAX_BELOW_EMA8_PCT: n(process.env.FIRST_ENTRY_CONFIRM_MAX_BELOW_EMA8_PCT, 0.08),
  FIRST_ENTRY_WEAK_BLOCK_ENABLED: b(process.env.FIRST_ENTRY_WEAK_BLOCK_ENABLED, true),
  FIRST_ENTRY_BLOCK_MIN_RED_FLAGS: n(process.env.FIRST_ENTRY_BLOCK_MIN_RED_FLAGS, 2),
  FIRST_ENTRY_BLOCK_RSI_BELOW: n(process.env.FIRST_ENTRY_BLOCK_RSI_BELOW, 50),
  FIRST_ENTRY_BLOCK_ADX_BELOW: n(process.env.FIRST_ENTRY_BLOCK_ADX_BELOW, 12),
  FIRST_ENTRY_BLOCK_MAX_CHASE_PCT: n(process.env.FIRST_ENTRY_BLOCK_MAX_CHASE_PCT, 0.45),
  FIRST_ENTRY_BLOCK_MAX_EXT_EMA18_PCT: n(process.env.FIRST_ENTRY_BLOCK_MAX_EXT_EMA18_PCT, 1.35),
  FIRST_ENTRY_BLOCK_IF_EMA8_BELOW_EMA18: b(process.env.FIRST_ENTRY_BLOCK_IF_EMA8_BELOW_EMA18, true),
  FIRST_ENTRY_BLOCK_IF_CLOSE_BELOW_EMA8: b(process.env.FIRST_ENTRY_BLOCK_IF_CLOSE_BELOW_EMA8, false),
  FIRST_ENTRY_BLOCK_IF_STRONG_BEARISH_FVVO: b(process.env.FIRST_ENTRY_BLOCK_IF_STRONG_BEARISH_FVVO, true),
  FIRST_ENTRY_BLOCK_IF_RECENT_BEARISH_RAY: b(process.env.FIRST_ENTRY_BLOCK_IF_RECENT_BEARISH_RAY, true),
  FIRST_ENTRY_RECENT_BEARISH_RAY_SEC: n(process.env.FIRST_ENTRY_RECENT_BEARISH_RAY_SEC, 300),
  FIRST_ENTRY_LOG_DEBUG: b(process.env.FIRST_ENTRY_LOG_DEBUG, true),

  BREAKOUT_MEMORY_ENABLED: b(process.env.BREAKOUT_MEMORY_ENABLED, true),
  BREAKOUT_MEMORY_BARS: n(process.env.BREAKOUT_MEMORY_BARS, 4),
  BREAKOUT_MEMORY_MAX_CHASE_PCT: n(process.env.BREAKOUT_MEMORY_MAX_CHASE_PCT, 0.25),
  BREAKOUT_MEMORY_REQUIRE_ABOVE_RECLAIM: b(process.env.BREAKOUT_MEMORY_REQUIRE_ABOVE_RECLAIM, true),
  BREAKOUT_MEMORY_INVALIDATE_PCT: n(process.env.BREAKOUT_MEMORY_INVALIDATE_PCT, 0.1),

  HARD_STOP_PCT: n(process.env.HARD_STOP_PCT, 0.8),
  BREAKEVEN_ARM_PCT: n(process.env.BREAKEVEN_ARM_PCT, 0.4),
  BREAKEVEN_OFFSET_PCT: n(process.env.BREAKEVEN_OFFSET_PCT, 0.05),
  PROFIT_LOCK_ARM_PCT: n(process.env.PROFIT_LOCK_ARM_PCT, 0.6),
  PROFIT_LOCK_GIVEBACK_PCT: n(process.env.PROFIT_LOCK_GIVEBACK_PCT, 0.35),
  TRAIL_ARM_PCT: n(process.env.TRAIL_ARM_PCT, 1.0),
  TRAIL_GIVEBACK_PCT: n(process.env.TRAIL_GIVEBACK_PCT, 0.45),

  EXIT_ON_BEARISH_TREND_CHANGE: b(process.env.EXIT_ON_BEARISH_TREND_CHANGE, true),
  EXIT_ON_BEARISH_TREND_CONTINUATION: b(process.env.EXIT_ON_BEARISH_TREND_CONTINUATION, false),
  EXIT_ON_5M_CLOSE_BELOW_EMA8: b(process.env.EXIT_ON_5M_CLOSE_BELOW_EMA8, true),
  EXIT_ON_5M_CLOSE_BELOW_EMA18: b(process.env.EXIT_ON_5M_CLOSE_BELOW_EMA18, false),

  LOCAL_TP_EXIT_ENABLED: b(process.env.LOCAL_TP_EXIT_ENABLED, true),
  LOCAL_TP_MIN_PROFIT_PCT: n(process.env.LOCAL_TP_MIN_PROFIT_PCT, 0.6),
  LOCAL_TP_EXIT_ON_CLOSE_BELOW_EMA8: b(process.env.LOCAL_TP_EXIT_ON_CLOSE_BELOW_EMA8, true),
  KEEP_BULL_CONTEXT_ON_TP_EXIT: b(process.env.KEEP_BULL_CONTEXT_ON_TP_EXIT, true),
  LOCAL_TP_EMA8_BUFFER_PCT: n(process.env.LOCAL_TP_EMA8_BUFFER_PCT, 0.1),
  LOCAL_TP_MIN_RSI_TO_HOLD: n(process.env.LOCAL_TP_MIN_RSI_TO_HOLD, 60),
  LOCAL_TP_MIN_ADX_TO_HOLD: n(process.env.LOCAL_TP_MIN_ADX_TO_HOLD, 35),
  LOCAL_TP_STRONG_ADX_HARD_BLOCK: n(process.env.LOCAL_TP_STRONG_ADX_HARD_BLOCK, 35),
  LOCAL_TP_BLOCK_IF_BULLISH_FVVO: b(process.env.LOCAL_TP_BLOCK_IF_BULLISH_FVVO, true),
  LOCAL_TP_FORCE_ALLOW_IF_CLOSE_BELOW_EMA18: b(process.env.LOCAL_TP_FORCE_ALLOW_IF_CLOSE_BELOW_EMA18, true),
  LOCAL_TP_FORCE_ALLOW_IF_BEARISH_FVVO: b(process.env.LOCAL_TP_FORCE_ALLOW_IF_BEARISH_FVVO, true),
  LOCAL_TP_FORCE_ALLOW_ON_TWO_WEAKENING_BARS: b(process.env.LOCAL_TP_FORCE_ALLOW_ON_TWO_WEAKENING_BARS, true),
  LOCAL_TP_REQUIRE_TWO_WEAKENING_BARS_IN_STRONG_TREND: b(
    process.env.LOCAL_TP_REQUIRE_TWO_WEAKENING_BARS_IN_STRONG_TREND,
    true
  ),
  LOCAL_TP_RSI_WEAKNESS_THRESHOLD: n(process.env.LOCAL_TP_RSI_WEAKNESS_THRESHOLD, 54),
  LOCAL_TP_RSI_WEAKNESS_THRESHOLD_STRONG_TREND: n(process.env.LOCAL_TP_RSI_WEAKNESS_THRESHOLD_STRONG_TREND, 52),
  LOCAL_TP_REQUIRE_CLOSE_BELOW_EMA18_OR_2_WEAK_BARS: b(
    process.env.LOCAL_TP_REQUIRE_CLOSE_BELOW_EMA18_OR_2_WEAK_BARS,
    true
  ),
  LOCAL_TP_STRONG_TREND_HARD_HOLD_ENABLED: b(process.env.LOCAL_TP_STRONG_TREND_HARD_HOLD_ENABLED, true),
  LOCAL_TP_STRONG_TREND_HARD_HOLD_MIN_ADX: n(process.env.LOCAL_TP_STRONG_TREND_HARD_HOLD_MIN_ADX, 35),
  LOCAL_TP_STRONG_TREND_HARD_HOLD_REQUIRE_EMA8_ABOVE_EMA18: b(
    process.env.LOCAL_TP_STRONG_TREND_HARD_HOLD_REQUIRE_EMA8_ABOVE_EMA18,
    true
  ),
  LOCAL_TP_STRONG_TREND_HARD_HOLD_REQUIRE_RSI_ABOVE: n(
    process.env.LOCAL_TP_STRONG_TREND_HARD_HOLD_REQUIRE_RSI_ABOVE,
    55
  ),
  LOCAL_TP_STRONG_TREND_ALLOW_ONLY_IF_CLOSE_BELOW_EMA18: b(
    process.env.LOCAL_TP_STRONG_TREND_ALLOW_ONLY_IF_CLOSE_BELOW_EMA18,
    true
  ),
  LOCAL_TP_STRONG_TREND_ALLOW_IF_TWO_WEAK_BARS_AND_RSI_WEAK: b(
    process.env.LOCAL_TP_STRONG_TREND_ALLOW_IF_TWO_WEAK_BARS_AND_RSI_WEAK,
    true
  ),
  LOCAL_TP_STRONG_TREND_RSI_WEAK_MAX: n(process.env.LOCAL_TP_STRONG_TREND_RSI_WEAK_MAX, 52),
  LOCAL_TP_STRICT_STRONG_TREND_GATE_ENABLED: b(process.env.LOCAL_TP_STRICT_STRONG_TREND_GATE_ENABLED, true),
  LOCAL_TP_STRICT_STRONG_TREND_MIN_ADX: n(process.env.LOCAL_TP_STRICT_STRONG_TREND_MIN_ADX, 35),
  LOCAL_TP_STRICT_STRONG_TREND_REQUIRE_EMA8_GT_EMA18: b(
    process.env.LOCAL_TP_STRICT_STRONG_TREND_REQUIRE_EMA8_GT_EMA18,
    true
  ),
  LOCAL_TP_STRICT_STRONG_TREND_REQUIRE_CLOSE_BELOW_EMA18: b(
    process.env.LOCAL_TP_STRICT_STRONG_TREND_REQUIRE_CLOSE_BELOW_EMA18,
    false
  ),
  LOCAL_TP_STRICT_STRONG_TREND_ALLOW_TWO_WEAK_BARS_AND_RSI_WEAK: b(
    process.env.LOCAL_TP_STRICT_STRONG_TREND_ALLOW_TWO_WEAK_BARS_AND_RSI_WEAK,
    true
  ),
  LOCAL_TP_STRICT_STRONG_TREND_RSI_WEAK_MAX: n(process.env.LOCAL_TP_STRICT_STRONG_TREND_RSI_WEAK_MAX, 52),
  LOCAL_TP_STRICT_STRONG_TREND_REQUIRE_TWO_WEAK_BARS: b(
    process.env.LOCAL_TP_STRICT_STRONG_TREND_REQUIRE_TWO_WEAK_BARS,
    true
  ),

  STRONG_TREND_HOLD_ENABLED: b(process.env.STRONG_TREND_HOLD_ENABLED, true),
  STRONG_TREND_HOLD_MIN_RSI: n(process.env.STRONG_TREND_HOLD_MIN_RSI, 64),
  STRONG_TREND_HOLD_MIN_ADX: n(process.env.STRONG_TREND_HOLD_MIN_ADX, 30),
  STRONG_TREND_HOLD_BLOCK_LOCAL_TP: b(process.env.STRONG_TREND_HOLD_BLOCK_LOCAL_TP, true),
  STRONG_TREND_HOLD_BLOCK_IF_BEARISH_FVVO: b(process.env.STRONG_TREND_HOLD_BLOCK_IF_BEARISH_FVVO, false),

  TOP_HARVEST_ENABLED: b(process.env.TOP_HARVEST_ENABLED, false),
  REENTRY_TOP_HARVEST_ENABLED: b(process.env.REENTRY_TOP_HARVEST_ENABLED, true),
  REENTRY_TOP_HARVEST_MIN_PROFIT_PCT: n(process.env.REENTRY_TOP_HARVEST_MIN_PROFIT_PCT, 0.55),
  REENTRY_TOP_HARVEST_MIN_ADX: n(process.env.REENTRY_TOP_HARVEST_MIN_ADX, 28),
  REENTRY_TOP_HARVEST_MIN_RSI_RECENT_HIGH: n(process.env.REENTRY_TOP_HARVEST_MIN_RSI_RECENT_HIGH, 64),
  REENTRY_TOP_HARVEST_MIN_EXT_FROM_EMA8_PCT: n(process.env.REENTRY_TOP_HARVEST_MIN_EXT_FROM_EMA8_PCT, 0.25),
  REENTRY_TOP_HARVEST_MIN_EXT_FROM_EMA18_PCT: n(process.env.REENTRY_TOP_HARVEST_MIN_EXT_FROM_EMA18_PCT, 0.4),
  REENTRY_TOP_HARVEST_REQUIRE_RSI_ROLLDOWN: b(process.env.REENTRY_TOP_HARVEST_REQUIRE_RSI_ROLLDOWN, true),
  REENTRY_TOP_HARVEST_ALLOW_ONE_WEAK_BAR: b(process.env.REENTRY_TOP_HARVEST_ALLOW_ONE_WEAK_BAR, true),
  REENTRY_TOP_HARVEST_ALLOW_TWO_WEAK_BARS: b(process.env.REENTRY_TOP_HARVEST_ALLOW_TWO_WEAK_BARS, true),
  REENTRY_TOP_HARVEST_ALLOW_BEARISH_FVVO_ACCELERATOR: b(
    process.env.REENTRY_TOP_HARVEST_ALLOW_BEARISH_FVVO_ACCELERATOR,
    true
  ),
  REENTRY_TOP_HARVEST_SOFT_ENABLED: b(process.env.REENTRY_TOP_HARVEST_SOFT_ENABLED, true),
  REENTRY_TOP_HARVEST_SOFT_MIN_PROFIT_PCT: n(process.env.REENTRY_TOP_HARVEST_SOFT_MIN_PROFIT_PCT, 0.5),
  REENTRY_TOP_HARVEST_SOFT_MIN_PEAK_PROFIT_PCT: n(process.env.REENTRY_TOP_HARVEST_SOFT_MIN_PEAK_PROFIT_PCT, 0.58),
  REENTRY_TOP_HARVEST_SOFT_MIN_ADX: n(process.env.REENTRY_TOP_HARVEST_SOFT_MIN_ADX, 30),
  REENTRY_TOP_HARVEST_SOFT_MIN_EXT_FROM_EMA8_PCT: n(process.env.REENTRY_TOP_HARVEST_SOFT_MIN_EXT_FROM_EMA8_PCT, 0.3),
  REENTRY_TOP_HARVEST_SOFT_MIN_EXT_FROM_EMA18_PCT: n(process.env.REENTRY_TOP_HARVEST_SOFT_MIN_EXT_FROM_EMA18_PCT, 0.5),
  REENTRY_TOP_HARVEST_SOFT_REQUIRE_BULLISH_FVVO_NOT_STRONG_NEGATIVE: b(
    process.env.REENTRY_TOP_HARVEST_SOFT_REQUIRE_BULLISH_FVVO_NOT_STRONG_NEGATIVE,
    true
  ),
  REENTRY_TOP_HARVEST_LOG_DEBUG: b(process.env.REENTRY_TOP_HARVEST_LOG_DEBUG, true),

  POST_EXIT_CONT_HARVEST_SOFT_ENABLED: b(process.env.POST_EXIT_CONT_HARVEST_SOFT_ENABLED, true),
  POST_EXIT_CONT_HARVEST_SOFT_MIN_PROFIT_PCT: n(process.env.POST_EXIT_CONT_HARVEST_SOFT_MIN_PROFIT_PCT, 0.5),
  POST_EXIT_CONT_HARVEST_SOFT_MIN_PEAK_PROFIT_PCT: n(process.env.POST_EXIT_CONT_HARVEST_SOFT_MIN_PEAK_PROFIT_PCT, 0.45),
  POST_EXIT_CONT_HARVEST_SOFT_MIN_ADX: n(process.env.POST_EXIT_CONT_HARVEST_SOFT_MIN_ADX, 28),
  POST_EXIT_CONT_HARVEST_SOFT_MIN_EXT_FROM_EMA8_PCT: n(process.env.POST_EXIT_CONT_HARVEST_SOFT_MIN_EXT_FROM_EMA8_PCT, 0.26),
  POST_EXIT_CONT_HARVEST_SOFT_MIN_EXT_FROM_EMA18_PCT: n(process.env.POST_EXIT_CONT_HARVEST_SOFT_MIN_EXT_FROM_EMA18_PCT, 0.42),
  POST_EXIT_CONT_HARVEST_SOFT_REQUIRE_NOT_STRONG_NEGATIVE_FVVO: b(
    process.env.POST_EXIT_CONT_HARVEST_SOFT_REQUIRE_NOT_STRONG_NEGATIVE_FVVO,
    true
  ),

  DYNAMIC_TP_ENABLED: b(process.env.DYNAMIC_TP_ENABLED, true),
  DTP_TIER1_ARM_PCT: n(process.env.DTP_TIER1_ARM_PCT, 0.6),
  DTP_TIER1_GIVEBACK_PCT: n(process.env.DTP_TIER1_GIVEBACK_PCT, 0.35),
  DTP_TIER2_ARM_PCT: n(process.env.DTP_TIER2_ARM_PCT, 1.2),
  DTP_TIER2_GIVEBACK_PCT: n(process.env.DTP_TIER2_GIVEBACK_PCT, 0.22),
  DTP_TIER3_ARM_PCT: n(process.env.DTP_TIER3_ARM_PCT, 1.8),
  DTP_TIER3_GIVEBACK_PCT: n(process.env.DTP_TIER3_GIVEBACK_PCT, 0.12),

  LAUNCH_TP_PROTECTION_ENABLED: b(process.env.LAUNCH_TP_PROTECTION_ENABLED, true),
  LAUNCH_TP_PROTECTION_BLOCK_TIER1: b(process.env.LAUNCH_TP_PROTECTION_BLOCK_TIER1, true),
  LAUNCH_TP_PROTECTION_MIN_PROFIT_PCT: n(process.env.LAUNCH_TP_PROTECTION_MIN_PROFIT_PCT, 0.9),
  LAUNCH_TP_PROTECTION_MIN_ADX: n(process.env.LAUNCH_TP_PROTECTION_MIN_ADX, 35),
  LAUNCH_TP_PROTECTION_MIN_RSI: n(process.env.LAUNCH_TP_PROTECTION_MIN_RSI, 60),
  LAUNCH_TP_PROTECTION_REQUIRE_PRICE_ABOVE_EMA8: b(process.env.LAUNCH_TP_PROTECTION_REQUIRE_PRICE_ABOVE_EMA8, true),
  LAUNCH_TP_PROTECTION_BLOCK_IF_BULLISH_FVVO: b(process.env.LAUNCH_TP_PROTECTION_BLOCK_IF_BULLISH_FVVO, true),
  LAUNCH_TP_PROTECTION_LOG: b(process.env.LAUNCH_TP_PROTECTION_LOG, true),

  POST_EXIT_CONT_TP_PROTECTION_ENABLED: b(process.env.POST_EXIT_CONT_TP_PROTECTION_ENABLED, true),
  POST_EXIT_CONT_TP_PROTECTION_BLOCK_TIER1: b(process.env.POST_EXIT_CONT_TP_PROTECTION_BLOCK_TIER1, true),
  POST_EXIT_CONT_TP_PROTECTION_MAX_PROTECT_PROFIT_PCT: n(process.env.POST_EXIT_CONT_TP_PROTECTION_MAX_PROTECT_PROFIT_PCT, 0.3),
  POST_EXIT_CONT_TP_PROTECTION_MIN_ADX: n(process.env.POST_EXIT_CONT_TP_PROTECTION_MIN_ADX, 28),
  POST_EXIT_CONT_TP_PROTECTION_MIN_RSI: n(process.env.POST_EXIT_CONT_TP_PROTECTION_MIN_RSI, 58),
  POST_EXIT_CONT_TP_PROTECTION_REQUIRE_PRICE_ABOVE_EMA8: b(process.env.POST_EXIT_CONT_TP_PROTECTION_REQUIRE_PRICE_ABOVE_EMA8, true),
  POST_EXIT_CONT_TP_PROTECTION_BLOCK_IF_BULLISH_FVVO: b(process.env.POST_EXIT_CONT_TP_PROTECTION_BLOCK_IF_BULLISH_FVVO, true),
  POST_EXIT_CONT_TP_PROTECTION_LOG: b(process.env.POST_EXIT_CONT_TP_PROTECTION_LOG, true),

  // v5.1 post-exit continuation profit guard
  POST_EXIT_CONT_PROFIT_GUARD_ENABLED: b(process.env.POST_EXIT_CONT_PROFIT_GUARD_ENABLED, true),
  POST_EXIT_CONT_PROFIT_GUARD_ARM_PEAK_PCT: n(process.env.POST_EXIT_CONT_PROFIT_GUARD_ARM_PEAK_PCT, 0.55),
  POST_EXIT_CONT_PROFIT_GUARD_LOCK_PCT: n(process.env.POST_EXIT_CONT_PROFIT_GUARD_LOCK_PCT, 0.45),
  POST_EXIT_CONT_PROFIT_GUARD_GIVEBACK_PCT: n(process.env.POST_EXIT_CONT_PROFIT_GUARD_GIVEBACK_PCT, 0.12),
  POST_EXIT_CONT_PROFIT_GUARD_MIN_CURRENT_PCT: n(process.env.POST_EXIT_CONT_PROFIT_GUARD_MIN_CURRENT_PCT, 0.20),
  POST_EXIT_CONT_PROFIT_GUARD_LOG: b(process.env.POST_EXIT_CONT_PROFIT_GUARD_LOG, true),

  PHASE2_REENTRY_ENABLED: b(process.env.PHASE2_REENTRY_ENABLED, true),
  MAX_REENTRIES_PER_BULL_REGIME: n(process.env.MAX_REENTRIES_PER_BULL_REGIME, 3),
  REENTRY_MIN_BARS_AFTER_EXIT: n(process.env.REENTRY_MIN_BARS_AFTER_EXIT, 1),
  REENTRY_REQUIRE_BULL_CONTEXT: b(process.env.REENTRY_REQUIRE_BULL_CONTEXT, true),
  REENTRY_REQUIRE_CLOSE_ABOVE_EMA8: b(process.env.REENTRY_REQUIRE_CLOSE_ABOVE_EMA8, true),
  REENTRY_MAX_CHASE_PCT: n(process.env.REENTRY_MAX_CHASE_PCT, 0.2),
  REENTRY_MIN_RESET_FROM_PEAK_PCT: n(process.env.REENTRY_MIN_RESET_FROM_PEAK_PCT, 0.15),
  FAST_REENTRY_ENABLED: b(process.env.FAST_REENTRY_ENABLED, true),
  FAST_REENTRY_MIN_RESET_FROM_PEAK_PCT: n(process.env.FAST_REENTRY_MIN_RESET_FROM_PEAK_PCT, 0.2),
  FAST_REENTRY_REQUIRE_CLOSE_ABOVE_EMA8: b(process.env.FAST_REENTRY_REQUIRE_CLOSE_ABOVE_EMA8, true),
  FAST_REENTRY_MAX_CHASE_PCT: n(process.env.FAST_REENTRY_MAX_CHASE_PCT, 0.18),
  FAST_REENTRY_MIN_RSI: n(process.env.FAST_REENTRY_MIN_RSI, 50),
  FAST_REENTRY_MIN_ADX: n(process.env.FAST_REENTRY_MIN_ADX, 14),
  FAST_REENTRY_REQUIRE_BULL_CONTEXT: b(process.env.FAST_REENTRY_REQUIRE_BULL_CONTEXT, true),
  STRONG_REENTRY_OVERRIDE_ENABLED: b(process.env.STRONG_REENTRY_OVERRIDE_ENABLED, true),
  STRONG_REENTRY_MIN_RSI: n(process.env.STRONG_REENTRY_MIN_RSI, 60),
  STRONG_REENTRY_MIN_ADX: n(process.env.STRONG_REENTRY_MIN_ADX, 30),
  STRONG_REENTRY_MAX_CHASE_PCT: n(process.env.STRONG_REENTRY_MAX_CHASE_PCT, 0.38),

  POST_EXIT_CONTINUATION_ENABLED: b(process.env.POST_EXIT_CONTINUATION_ENABLED, true),
  POST_EXIT_CONTINUATION_WINDOW_BARS: n(process.env.POST_EXIT_CONTINUATION_WINDOW_BARS, 8),
  POST_EXIT_CONTINUATION_MIN_PROFIT_EXIT_PCT: n(process.env.POST_EXIT_CONTINUATION_MIN_PROFIT_EXIT_PCT, 0.5),
  POST_EXIT_CONTINUATION_MIN_RSI: n(process.env.POST_EXIT_CONTINUATION_MIN_RSI, 55),
  POST_EXIT_CONTINUATION_MIN_ADX: n(process.env.POST_EXIT_CONTINUATION_MIN_ADX, 18),
  POST_EXIT_CONTINUATION_STRONG_MIN_RSI: n(process.env.POST_EXIT_CONTINUATION_STRONG_MIN_RSI, 64),
  POST_EXIT_CONTINUATION_STRONG_MIN_ADX: n(process.env.POST_EXIT_CONTINUATION_STRONG_MIN_ADX, 30),
  POST_EXIT_CONTINUATION_MAX_CHASE_PCT: n(process.env.POST_EXIT_CONTINUATION_MAX_CHASE_PCT, 0.38),
  POST_EXIT_CONTINUATION_STRONG_MAX_CHASE_PCT: n(process.env.POST_EXIT_CONTINUATION_STRONG_MAX_CHASE_PCT, 0.6),
  POST_EXIT_CONTINUATION_MAX_EXT_FROM_EMA18_PCT: n(process.env.POST_EXIT_CONTINUATION_MAX_EXT_FROM_EMA18_PCT, 1.25),
  POST_EXIT_CONTINUATION_REQUIRE_CLOSE_ABOVE_EMA8: b(process.env.POST_EXIT_CONTINUATION_REQUIRE_CLOSE_ABOVE_EMA8, false),
  POST_EXIT_CONTINUATION_MAX_BELOW_EMA8_PCT: n(process.env.POST_EXIT_CONTINUATION_MAX_BELOW_EMA8_PCT, 0.06),
  POST_EXIT_CONTINUATION_REQUIRE_EMA8_ABOVE_EMA18: b(process.env.POST_EXIT_CONTINUATION_REQUIRE_EMA8_ABOVE_EMA18, true),
  POST_EXIT_CONTINUATION_REQUIRE_BULLISH_RAY_RECENCY: b(process.env.POST_EXIT_CONTINUATION_REQUIRE_BULLISH_RAY_RECENCY, false),
  POST_EXIT_CONTINUATION_REQUIRE_BULLISH_RAY_RECENCY_SEC: n(process.env.POST_EXIT_CONTINUATION_REQUIRE_BULLISH_RAY_RECENCY_SEC, 1800),
  POST_EXIT_CONTINUATION_ALLOW_FVVO_NEUTRAL: b(process.env.POST_EXIT_CONTINUATION_ALLOW_FVVO_NEUTRAL, true),
  POST_EXIT_CONTINUATION_BLOCK_ON_BURST_BEARISH: b(process.env.POST_EXIT_CONTINUATION_BLOCK_ON_BURST_BEARISH, true),
  POST_EXIT_CONTINUATION_IGNORE_SNIPER_SELL_IF_STRONG: b(process.env.POST_EXIT_CONTINUATION_IGNORE_SNIPER_SELL_IF_STRONG, true),

  TREND_CHANGE_LAUNCH_ENABLED: b(process.env.TREND_CHANGE_LAUNCH_ENABLED, true),
  TREND_CHANGE_LAUNCH_MIN_RSI: n(process.env.TREND_CHANGE_LAUNCH_MIN_RSI, 60),
  TREND_CHANGE_LAUNCH_MIN_ADX: n(process.env.TREND_CHANGE_LAUNCH_MIN_ADX, 14),
  TREND_CHANGE_LAUNCH_MAX_CHASE_PCT: n(process.env.TREND_CHANGE_LAUNCH_MAX_CHASE_PCT, 0.35),
  TREND_CHANGE_LAUNCH_MAX_EXT_FROM_EMA18_PCT: n(process.env.TREND_CHANGE_LAUNCH_MAX_EXT_FROM_EMA18_PCT, 1.2),
  TREND_CHANGE_LAUNCH_MEMORY_BARS: n(process.env.TREND_CHANGE_LAUNCH_MEMORY_BARS, 2),
  DEFERRED_LAUNCH_MIN_RSI: n(process.env.DEFERRED_LAUNCH_MIN_RSI, 68),
  DEFERRED_LAUNCH_MIN_ADX: n(process.env.DEFERRED_LAUNCH_MIN_ADX, 18),
  STRONG_LAUNCH_OVERRIDE_ENABLED: b(process.env.STRONG_LAUNCH_OVERRIDE_ENABLED, true),
  STRONG_LAUNCH_MIN_RSI: n(process.env.STRONG_LAUNCH_MIN_RSI, 72),
  STRONG_LAUNCH_MIN_ADX: n(process.env.STRONG_LAUNCH_MIN_ADX, 24),
  STRONG_LAUNCH_MAX_CHASE_PCT: n(process.env.STRONG_LAUNCH_MAX_CHASE_PCT, 0.55),
  STRONG_LAUNCH_MAX_EXT_FROM_EMA18_PCT: n(process.env.STRONG_LAUNCH_MAX_EXT_FROM_EMA18_PCT, 1.35),
  FAST_TICK_LAUNCH_ENABLED: b(process.env.FAST_TICK_LAUNCH_ENABLED, true),
  FAST_TICK_LAUNCH_WINDOW_SEC: n(process.env.FAST_TICK_LAUNCH_WINDOW_SEC, 45),
  FAST_TICK_LAUNCH_MIN_RSI: n(process.env.FAST_TICK_LAUNCH_MIN_RSI, 56),
  FAST_TICK_LAUNCH_MIN_ADX: n(process.env.FAST_TICK_LAUNCH_MIN_ADX, 18),
  FAST_TICK_LAUNCH_CONFIRM_PCT: n(process.env.FAST_TICK_LAUNCH_CONFIRM_PCT, 0.05),
  FAST_TICK_LAUNCH_MAX_CHASE_PCT: n(process.env.FAST_TICK_LAUNCH_MAX_CHASE_PCT, 0.35),
  FAST_TICK_LAUNCH_MIN_TICKS_ABOVE_CONFIRM: n(process.env.FAST_TICK_LAUNCH_MIN_TICKS_ABOVE_CONFIRM, 2),
  FAST_TICK_LAUNCH_STRONG_MIN_RSI: n(process.env.FAST_TICK_LAUNCH_STRONG_MIN_RSI, 60),
  FAST_TICK_LAUNCH_STRONG_MIN_ADX: n(process.env.FAST_TICK_LAUNCH_STRONG_MIN_ADX, 22),
  FAST_TICK_LAUNCH_STRONG_MAX_CHASE_PCT: n(process.env.FAST_TICK_LAUNCH_STRONG_MAX_CHASE_PCT, 0.45),
  DEFERRED_SLOW_RAMP_OVERRIDE_ENABLED: b(process.env.DEFERRED_SLOW_RAMP_OVERRIDE_ENABLED, true),
  DEFERRED_SLOW_RAMP_MIN_RSI: n(process.env.DEFERRED_SLOW_RAMP_MIN_RSI, 62),
  DEFERRED_SLOW_RAMP_MIN_ADX: n(process.env.DEFERRED_SLOW_RAMP_MIN_ADX, 20),
  DEFERRED_SLOW_RAMP_MAX_CHASE_PCT: n(process.env.DEFERRED_SLOW_RAMP_MAX_CHASE_PCT, 0.25),
  DEFERRED_SLOW_RAMP_MAX_EXT_FROM_EMA18_PCT: n(process.env.DEFERRED_SLOW_RAMP_MAX_EXT_FROM_EMA18_PCT, 0.6),

  ELEVATED_CONTINUATION_ENABLED: b(process.env.ELEVATED_CONTINUATION_ENABLED, true),
  ELEVATED_CONTINUATION_WINDOW_BARS: n(process.env.ELEVATED_CONTINUATION_WINDOW_BARS, 6),
  ELEVATED_CONTINUATION_MIN_RSI: n(process.env.ELEVATED_CONTINUATION_MIN_RSI, 58),
  ELEVATED_CONTINUATION_MIN_ADX: n(process.env.ELEVATED_CONTINUATION_MIN_ADX, 18),
  ELEVATED_CONTINUATION_MAX_CHASE_PCT: n(process.env.ELEVATED_CONTINUATION_MAX_CHASE_PCT, 0.52),
  ELEVATED_CONTINUATION_MAX_EXT_FROM_EMA18_PCT: n(process.env.ELEVATED_CONTINUATION_MAX_EXT_FROM_EMA18_PCT, 0.95),
  ELEVATED_CONTINUATION_MIN_EMA8_SLOPE_PCT: n(process.env.ELEVATED_CONTINUATION_MIN_EMA8_SLOPE_PCT, 0.03),
  ELEVATED_CONTINUATION_REQUIRE_CLOSE_ABOVE_EMA8: b(process.env.ELEVATED_CONTINUATION_REQUIRE_CLOSE_ABOVE_EMA8, true),
  ELEVATED_CONTINUATION_ALLOW_NEGATIVE_FVVO_IF_STRONG: b(process.env.ELEVATED_CONTINUATION_ALLOW_NEGATIVE_FVVO_IF_STRONG, true),

  FVVO_ENABLED: b(process.env.FVVO_ENABLED, true),
  FVVO_MEMORY_SEC: n(process.env.FVVO_MEMORY_SEC, 1800),
  FVVO_SNIPER_BUY_BOOST: n(process.env.FVVO_SNIPER_BUY_BOOST, 1),
  FVVO_BURST_BULLISH_BOOST: n(process.env.FVVO_BURST_BULLISH_BOOST, 2),
  FVVO_SNIPER_SELL_PENALTY: n(process.env.FVVO_SNIPER_SELL_PENALTY, 1),
  FVVO_BURST_BEARISH_PENALTY: n(process.env.FVVO_BURST_BEARISH_PENALTY, 2),
  FVVO_REENTRY_RSI_RELAX: n(process.env.FVVO_REENTRY_RSI_RELAX, 3),
  FVVO_REENTRY_MAX_CHASE_BONUS_PCT: n(process.env.FVVO_REENTRY_MAX_CHASE_BONUS_PCT, 0.08),
  FVVO_CONT_RSI_RELAX: n(process.env.FVVO_CONT_RSI_RELAX, 2),
  FVVO_CONT_MAX_CHASE_BONUS_PCT: n(process.env.FVVO_CONT_MAX_CHASE_BONUS_PCT, 0.06),
  FVVO_LAUNCH_RSI_RELAX: n(process.env.FVVO_LAUNCH_RSI_RELAX, 2),
  FVVO_LAUNCH_MAX_CHASE_BONUS_PCT: n(process.env.FVVO_LAUNCH_MAX_CHASE_BONUS_PCT, 0.05),
  FVVO_SNIPER_SELL_CHASE_PENALTY_PCT: n(process.env.FVVO_SNIPER_SELL_CHASE_PENALTY_PCT, 0.08),
  FVVO_BURST_BEARISH_CHASE_PENALTY_PCT: n(process.env.FVVO_BURST_BEARISH_CHASE_PENALTY_PCT, 0.1),
};
