import express from "express";

import { CONFIG } from "./src/config.js";
import { getRootStatus, getStatus, resetBrain, handleWebhook } from "./src/brain.js";
import { log } from "./src/stateStore.js";
import { s } from "./src/utils.js";

const app = express();
app.use(express.json({ limit: "1mb" }));

app.get("/", (_req, res) => {
  res.json(getRootStatus());
});

app.get("/health", (_req, res) => {
  res.json(getRootStatus());
});

app.get("/status", (_req, res) => {
  res.json(getStatus());
});

app.post("/reset", (req, res) => {
  const reason = s(req.body?.reason, "manual_reset");
  res.json(resetBrain(reason));
});

app.post(CONFIG.WEBHOOK_PATH, (req, res) => {
  const result = handleWebhook(req.body || {});
  res.status(result.status || 200).json(result.json);
});

app.listen(CONFIG.PORT, () => {
  log("✅ brain listening", { port: CONFIG.PORT, path: CONFIG.WEBHOOK_PATH, symbol: CONFIG.SYMBOL, tf: CONFIG.ENTRY_TF, brain: CONFIG.BRAIN_NAME });
  log("🧠 CONFIG_SNAPSHOT", {
    brain: CONFIG.BRAIN_NAME,
    port: CONFIG.PORT,
    path: CONFIG.WEBHOOK_PATH,
    symbol: CONFIG.SYMBOL,
    tf: CONFIG.ENTRY_TF,
    enableHttpForward: CONFIG.ENABLE_HTTP_FORWARD,
    replayAllowStaleData: CONFIG.REPLAY_ALLOW_STALE_DATA,
    replayUseEventTimeForPositionClock: CONFIG.REPLAY_USE_EVENT_TIME_FOR_POSITION_CLOCK,
    webhookRxLog: {
      enabled: CONFIG.WEBHOOK_RX_LOG_ENABLED,
      logBody: CONFIG.WEBHOOK_RX_LOG_BODY,
      families: CONFIG.WEBHOOK_RX_LOG_FAMILIES,
    },
    rayFeatureSyncWait: {
      enabled: CONFIG.RAY_FEATURE_SYNC_WAIT_ENABLED,
      mode: CONFIG.RAY_FEATURE_SYNC_MODE,
      waitMs: CONFIG.RAY_FEATURE_SYNC_WAIT_MS,
      closeAlertGraceSec: CONFIG.RAY_FEATURE_SYNC_CLOSE_ALERT_GRACE_SEC,
      events: CONFIG.RAY_FEATURE_SYNC_EVENTS,
      probeLogEnabled: CONFIG.RAY_PROBE_LOG_ENABLED,
    },
    fvvoDirectEventShadow: {
      probeLogEnabled: CONFIG.FVVO_PROBE_LOG_ENABLED,
      directEventShadowEnabled: CONFIG.FVVO_DIRECT_EVENT_SHADOW_ENABLED,
      ttlSec: CONFIG.FVVO_DIRECT_EVENT_TTL_SEC,
      acceptTf: CONFIG.FVVO_DIRECT_EVENT_ACCEPT_TF,
      featureSyncWaitEnabled: CONFIG.FVVO_FEATURE_SYNC_WAIT_ENABLED,
      featureSyncMode: CONFIG.FVVO_FEATURE_SYNC_MODE,
      featureSyncWaitMs: CONFIG.FVVO_FEATURE_SYNC_WAIT_MS,
      featureSyncCloseAlertGraceSec: CONFIG.FVVO_FEATURE_SYNC_CLOSE_ALERT_GRACE_SEC,
      opbUpdateRealMemory: CONFIG.FVVO_OPB_UPDATE_REAL_MEMORY,
      earlyShadowEnabled: CONFIG.EARLY_FVVO_ENTRY_SHADOW_ENABLED,
      requireBullContext: CONFIG.EARLY_FVVO_ENTRY_SHADOW_REQUIRE_BULL_CONTEXT,
      minRsi: CONFIG.EARLY_FVVO_ENTRY_SHADOW_MIN_RSI,
      minAdx: CONFIG.EARLY_FVVO_ENTRY_SHADOW_MIN_ADX,
      maxExt18Pct: CONFIG.EARLY_FVVO_ENTRY_SHADOW_MAX_EXT18_PCT,
      maxChasePct: CONFIG.EARLY_FVVO_ENTRY_SHADOW_MAX_CHASE_PCT,
      requireCloseAboveEma8: CONFIG.EARLY_FVVO_ENTRY_SHADOW_REQUIRE_CLOSE_ABOVE_EMA8,
      requireEma8AboveEma18: CONFIG.EARLY_FVVO_ENTRY_SHADOW_REQUIRE_EMA8_ABOVE_EMA18,
      blockBearishFvvo: CONFIG.EARLY_FVVO_ENTRY_SHADOW_BLOCK_BEARISH_FVVO,
      shadowScorecard: {
        enabled: CONFIG.FVVO_SHADOW_SCORECARD_ENABLED,
        includeProbes: CONFIG.FVVO_SHADOW_SCORECARD_INCLUDE_PROBES,
        maxBars: CONFIG.FVVO_SHADOW_SCORECARD_MAX_BARS,
        targetsPct: CONFIG.FVVO_SHADOW_SCORECARD_TARGETS_PCT,
        tickEnabled: CONFIG.FVVO_SHADOW_SCORECARD_TICK_ENABLED,
        tickTargetPct: CONFIG.FVVO_SHADOW_SCORECARD_TICK_TARGET_PCT,
        tickAdversePct: CONFIG.FVVO_SHADOW_SCORECARD_TICK_ADVERSE_PCT,
      },
      bearishInvalidationShadow: {
        enabled: CONFIG.FVVO_BEARISH_INVALIDATION_SHADOW_ENABLED,
        recencySec: CONFIG.FVVO_BEARISH_INVALIDATION_RECENCY_SEC,
        minRsi: CONFIG.FVVO_BEARISH_INVALIDATION_MIN_RSI,
        minAdx: CONFIG.FVVO_BEARISH_INVALIDATION_MIN_ADX,
        requireCloseAboveEma8: CONFIG.FVVO_BEARISH_INVALIDATION_REQUIRE_CLOSE_ABOVE_EMA8,
        requireEma8AboveEma18OrImproving: CONFIG.FVVO_BEARISH_INVALIDATION_REQUIRE_EMA8_ABOVE_EMA18_OR_IMPROVING,
        requirePositiveFlow: CONFIG.FVVO_BEARISH_INVALIDATION_REQUIRE_POSITIVE_FLOW,
        minFlowScore: CONFIG.FVVO_BEARISH_INVALIDATION_MIN_FLOW_SCORE,
      },
    },
    rayBlockScorecard: {
      enabled: CONFIG.RAY_BLOCK_SCORECARD_ENABLED,
      maxBars: CONFIG.RAY_BLOCK_SCORECARD_MAX_BARS,
      windowsMin: CONFIG.RAY_BLOCK_SCORECARD_WINDOWS_MIN,
      tickEnabled: CONFIG.RAY_BLOCK_SCORECARD_TICK_ENABLED,
      tickTargetPct: CONFIG.RAY_BLOCK_SCORECARD_TICK_TARGET_PCT,
      tickAdversePct: CONFIG.RAY_BLOCK_SCORECARD_TICK_ADVERSE_PCT,
    },
    exitForwardRetry: {
      enabled: CONFIG.EXIT_FORWARD_RETRY_ENABLED,
      delaysMs: CONFIG.EXIT_FORWARD_RETRY_DELAYS_MS,
      blockEntries: CONFIG.EXIT_FORWARD_RETRY_BLOCK_ENTRIES,
    },
    firstEntry: {
      enabled: CONFIG.FIRST_ENTRY_ENGINE_ENABLED,
      immediateMaxChasePct: CONFIG.FIRST_ENTRY_IMMEDIATE_MAX_CHASE_PCT,
      immediateMinRsi: CONFIG.FIRST_ENTRY_IMMEDIATE_MIN_RSI,
      immediateMinAdx: CONFIG.FIRST_ENTRY_IMMEDIATE_MIN_ADX,
      confirmEnabled: CONFIG.FIRST_ENTRY_CONFIRM_ENABLED,
      confirmWindowSec: CONFIG.FIRST_ENTRY_CONFIRM_WINDOW_SEC,
      confirmMinAdx: CONFIG.FIRST_ENTRY_CONFIRM_MIN_ADX,
      weakBlockEnabled: CONFIG.FIRST_ENTRY_WEAK_BLOCK_ENABLED,
      featureSyncEnabled: CONFIG.FIRST_ENTRY_FEATURE_SYNC_ENABLED,
      featureSyncGraceSec: CONFIG.FIRST_ENTRY_FEATURE_SYNC_GRACE_SEC,
      featureSyncMinFeatureLagSec: CONFIG.FIRST_ENTRY_FEATURE_SYNC_MIN_FEATURE_LAG_SEC,
      confirmMinTicks: CONFIG.FIRST_ENTRY_CONFIRM_MIN_TICKS,
      strongFeatureTicks: CONFIG.FIRST_ENTRY_CONFIRM_STRONG_FEATURE_TICKS,
      strongFeatureMinRsi: CONFIG.FIRST_ENTRY_CONFIRM_STRONG_MIN_RSI,
      strongFeatureMinAdx: CONFIG.FIRST_ENTRY_CONFIRM_STRONG_MIN_ADX,
      confirmUpgradeEnabled: CONFIG.FIRST_ENTRY_CONFIRM_UPGRADE_ENABLED,
      confirmUpgradeGraceSec: CONFIG.FIRST_ENTRY_CONFIRM_UPGRADE_GRACE_SEC,
      contextQualityBlock: {
        enabled: CONFIG.FIRST_ENTRY_CONTEXT_QUALITY_BLOCK_ENABLED,
        compressedRsiBelow: CONFIG.FIRST_ENTRY_COMPRESSED_RSI_BELOW,
        compressedAdxBelow: CONFIG.FIRST_ENTRY_COMPRESSED_ADX_BELOW,
        compressedEmaSpreadBelowPct: CONFIG.FIRST_ENTRY_COMPRESSED_EMA_SPREAD_BELOW_PCT,
        lateExtLowAdxEnabled: CONFIG.FIRST_ENTRY_LATE_EXT_LOW_ADX_ENABLED,
        lateExtAdxBelow: CONFIG.FIRST_ENTRY_LATE_EXT_ADX_BELOW,
        lateExtExt18AbovePct: CONFIG.FIRST_ENTRY_LATE_EXT_EXT18_ABOVE_PCT,
        lateExtRsiAbove: CONFIG.FIRST_ENTRY_LATE_EXT_RSI_ABOVE,
        lateExtAction: CONFIG.FIRST_ENTRY_LATE_EXT_ACTION,
        lateExtWatchBars: CONFIG.FIRST_ENTRY_LATE_EXT_WATCH_BARS,
        lateExtReentryAdxMin: CONFIG.FIRST_ENTRY_LATE_EXT_REENTRY_ADX_MIN,
        lateExtReentryEmaSpreadMinPct: CONFIG.FIRST_ENTRY_LATE_EXT_REENTRY_EMA_SPREAD_MIN_PCT,
      },
      deepRecoveryOverride: {
        enabled: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_OVERRIDE_ENABLED,
        lookbackBars: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_LOOKBACK_BARS,
        minDropPct: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_MIN_DROP_PCT,
        maxExt18Pct: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_MAX_EXT18_PCT,
        minRsi: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_MIN_RSI,
        minAdx: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_MIN_ADX,
        maxChasePct: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_MAX_CHASE_PCT,
        requireBullishFvvo: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_REQUIRE_BULLISH_FVVO,
        requireCloseAboveEma8: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_REQUIRE_CLOSE_ABOVE_EMA8,
        requireEma8AboveEma18: CONFIG.FIRST_ENTRY_DEEP_RECOVERY_REQUIRE_EMA8_ABOVE_EMA18,
      },
    },
    fastTickLaunch: {
      enabled: CONFIG.FAST_TICK_LAUNCH_ENABLED,
      windowSec: CONFIG.FAST_TICK_LAUNCH_WINDOW_SEC,
      requireArmContext: CONFIG.FAST_TICK_LAUNCH_REQUIRE_ARM_CONTEXT,
      armMinRsi: CONFIG.FAST_TICK_LAUNCH_ARM_MIN_RSI,
      armMinAdx: CONFIG.FAST_TICK_LAUNCH_ARM_MIN_ADX,
      requireCloseAboveEma8: CONFIG.FAST_TICK_LAUNCH_REQUIRE_CLOSE_ABOVE_EMA8,
      requireEma8AboveEma18: CONFIG.FAST_TICK_LAUNCH_REQUIRE_EMA8_ABOVE_EMA18,
      requireFvvoNonNegative: CONFIG.FAST_TICK_LAUNCH_REQUIRE_FVVO_NON_NEGATIVE,
      minRsi: CONFIG.FAST_TICK_LAUNCH_MIN_RSI,
      minAdx: CONFIG.FAST_TICK_LAUNCH_MIN_ADX,
      confirmPct: CONFIG.FAST_TICK_LAUNCH_CONFIRM_PCT,
      minTicksAboveConfirm: CONFIG.FAST_TICK_LAUNCH_MIN_TICKS_ABOVE_CONFIRM,
    },
    firstEntryFailFast: {
      enabled: CONFIG.FIRST_ENTRY_FAIL_FAST_ENABLED,
      bars: CONFIG.FIRST_ENTRY_FAIL_FAST_BARS,
      minHeldSec: CONFIG.FIRST_ENTRY_FAIL_FAST_MIN_HELD_SEC,
      maxHeldSec: CONFIG.FIRST_ENTRY_FAIL_FAST_MAX_HELD_SEC,
      rsiBelow: CONFIG.FIRST_ENTRY_FAIL_FAST_RSI_BELOW,
      minLossPct: CONFIG.FIRST_ENTRY_FAIL_FAST_MIN_LOSS_PCT,
      exitIfCloseBelowEma18: CONFIG.FIRST_ENTRY_FAIL_FAST_EXIT_IF_CLOSE_BELOW_EMA18,
      exitIfCloseBelowEma8: CONFIG.FIRST_ENTRY_FAIL_FAST_EXIT_IF_CLOSE_BELOW_EMA8,
    },
    firstEntryNoProgress: {
      enabled: CONFIG.FIRST_ENTRY_NO_PROGRESS_ENABLED,
      minBars: CONFIG.FIRST_ENTRY_NO_PROGRESS_MIN_BARS,
      maxBars: CONFIG.FIRST_ENTRY_NO_PROGRESS_MAX_BARS,
      minPeakPct: CONFIG.FIRST_ENTRY_NO_PROGRESS_MIN_PEAK_PCT,
      maxCurrentPct: CONFIG.FIRST_ENTRY_NO_PROGRESS_MAX_CURRENT_PCT,
      rsiBelow: CONFIG.FIRST_ENTRY_NO_PROGRESS_RSI_BELOW,
      exitIfCloseBelowEma8: CONFIG.FIRST_ENTRY_NO_PROGRESS_EXIT_IF_CLOSE_BELOW_EMA8,
      exitIfCloseBelowEma18: CONFIG.FIRST_ENTRY_NO_PROGRESS_EXIT_IF_CLOSE_BELOW_EMA18,
      requireNotBullishFvvo: CONFIG.FIRST_ENTRY_NO_PROGRESS_REQUIRE_NOT_BULLISH_FVVO,
    },
    firstEntryThesisFail: {
      enabled: CONFIG.FIRST_ENTRY_THESIS_FAIL_ENABLED,
      minBars: CONFIG.FIRST_ENTRY_THESIS_FAIL_MIN_BARS,
      maxBars: CONFIG.FIRST_ENTRY_THESIS_FAIL_MAX_BARS,
      minLossPct: CONFIG.FIRST_ENTRY_THESIS_FAIL_MIN_LOSS_PCT,
      maxPeakPct: CONFIG.FIRST_ENTRY_THESIS_FAIL_MAX_PEAK_PCT,
      rsiBelow: CONFIG.FIRST_ENTRY_THESIS_FAIL_RSI_BELOW,
      requireCloseBelowEma8: CONFIG.FIRST_ENTRY_THESIS_FAIL_REQUIRE_CLOSE_BELOW_EMA8,
      requireCloseBelowEma18: CONFIG.FIRST_ENTRY_THESIS_FAIL_REQUIRE_CLOSE_BELOW_EMA18,
      requireNotBullishFvvo: CONFIG.FIRST_ENTRY_THESIS_FAIL_REQUIRE_NOT_BULLISH_FVVO,
    },

    tier1ForceExitLoaded: {
      givebackPct: CONFIG.DYNAMIC_TP_TIER1_FORCE_EXIT_GIVEBACK_PCT,
      minExitPnlPct: CONFIG.DYNAMIC_TP_TIER1_MIN_EXIT_PNL_PCT,
      envShortGiveback: process.env.DYNAMIC_TP_TIER1_FORCE_GIVEBACK_PCT || null,
      envLongGiveback: process.env.DYNAMIC_TP_TIER1_FORCE_EXIT_GIVEBACK_PCT || null,
      envShortMinExit: process.env.DYNAMIC_TP_TIER1_FORCE_MIN_EXIT_PNL_PCT || null,
      envLongMinExit: process.env.DYNAMIC_TP_TIER1_MIN_EXIT_PNL_PCT || null,
    },

    dynamicBreakeven: {
      enabled: CONFIG.DYNAMIC_BREAKEVEN_ENABLED,
      weakArmPct: CONFIG.DYNAMIC_BE_WEAK_ARM_PCT,
      normalArmPct: CONFIG.DYNAMIC_BE_NORMAL_ARM_PCT,
      strongArmPct: CONFIG.DYNAMIC_BE_STRONG_ARM_PCT,
      weakOffsetPct: CONFIG.DYNAMIC_BE_WEAK_OFFSET_PCT,
      normalOffsetPct: CONFIG.DYNAMIC_BE_NORMAL_OFFSET_PCT,
      strongOffsetPct: CONFIG.DYNAMIC_BE_STRONG_OFFSET_PCT,
      weakMaxRsi: CONFIG.DYNAMIC_BE_WEAK_MAX_RSI,
      weakMaxAdx: CONFIG.DYNAMIC_BE_WEAK_MAX_ADX,
      strongMinRsi: CONFIG.DYNAMIC_BE_STRONG_MIN_RSI,
      strongMinAdx: CONFIG.DYNAMIC_BE_STRONG_MIN_ADX,
      strongLockEnabled: CONFIG.DYNAMIC_BE_STRONG_LOCK_ENABLED,
      strongLockArmPct: CONFIG.DYNAMIC_BE_STRONG_LOCK_ARM_PCT,
      strongLockPct: CONFIG.DYNAMIC_BE_STRONG_LOCK_PCT,
    },
    atrStructureStop: {
      enabled: CONFIG.ATR_STRUCTURE_STOP_ENABLED,
      multFirstEntry: CONFIG.ATR_STOP_MULT_FIRST_ENTRY,
      multReentry: CONFIG.ATR_STOP_MULT_REENTRY,
      multStrongReentry: CONFIG.ATR_STOP_MULT_STRONG_REENTRY,
      minPct: CONFIG.ATR_STOP_MIN_PCT,
      maxPct: CONFIG.ATR_STOP_MAX_PCT,
      updateOnlyInProfit: CONFIG.ATR_STOP_UPDATE_ONLY_IN_PROFIT,
      allowTightenOnly: CONFIG.ATR_STOP_ALLOW_TIGHTEN_ONLY,
      requireFeatureFresh: CONFIG.ATR_STOP_REQUIRE_FEATURE_FRESH,
      deriveIfMissing: CONFIG.ATR_STOP_DERIVE_IF_MISSING,
      applyFirstEntry: CONFIG.ATR_STOP_APPLY_FIRST_ENTRY,
      applyReentry: CONFIG.ATR_STOP_APPLY_REENTRY,
      applyOtherModes: CONFIG.ATR_STOP_APPLY_OTHER_MODES,
      minBarsAfterEntry: CONFIG.ATR_STOP_MIN_BARS_AFTER_ENTRY,
      minLossTriggerPct: CONFIG.ATR_STOP_MIN_LOSS_TRIGGER_PCT,
      useRecentLow: CONFIG.ATR_STRUCTURE_USE_RECENT_LOW,
      lookbackBars: CONFIG.ATR_STRUCTURE_LOOKBACK_BARS,
      bufferPct: CONFIG.ATR_STRUCTURE_BUFFER_PCT,
    },
    postExitProfitGuard: {
      enabled: CONFIG.POST_EXIT_CONT_PROFIT_GUARD_ENABLED,
      armPeakPct: CONFIG.POST_EXIT_CONT_PROFIT_GUARD_ARM_PEAK_PCT,
      lockPct: CONFIG.POST_EXIT_CONT_PROFIT_GUARD_LOCK_PCT,
      givebackPct: CONFIG.POST_EXIT_CONT_PROFIT_GUARD_GIVEBACK_PCT,
      minCurrentPct: CONFIG.POST_EXIT_CONT_PROFIT_GUARD_MIN_CURRENT_PCT,
    },
  });
});
