import express from "express";
import { CONFIG } from "./src/config.js";
import { S, loadState, resetState } from "./src/stateStore.js";
import { handleWebhook } from "./src/brain.js";
loadState();
const app = express(); app.use(express.json({ limit: "256kb" }));
app.get("/health", (_q, r) => r.json({ ok: true, brain: CONFIG.NAME, symbol: CONFIG.SYMBOL, shadow: !CONFIG.ENABLE_HTTP_FORWARD, phase: S.phase, inPosition: Boolean(S.position) }));
app.get("/state", (_q, r) => r.json(S));
app.post("/webhook", async (q, r) => { try { const out = await handleWebhook(q.body); r.status(out.status).json(out.body); } catch (e) { r.status(500).json({ ok: false, error: String(e.message || e) }); } });
app.post("/reset", (q, r) => { if (q.body?.secret !== CONFIG.WEBHOOK_SECRET) return r.status(403).json({ ok: false }); resetState(); r.json({ ok: true }); });
app.listen(CONFIG.PORT, () => console.log(`${CONFIG.NAME} listening on ${CONFIG.PORT}; shadow=${!CONFIG.ENABLE_HTTP_FORWARD}`));
