BRAIN_NAME="BrainRAY_Basic_Signal_v2.0"
PORT="8080"
DEBUG="1"
WEBHOOK_PATH="/webhook"

WEBHOOK_SECRET="CHANGE_ME_TO_RANDOM_40+CHARS_9f8d7c6b5a4e3d2c1b0a"

SYMBOL="BINANCE:SOLUSDT"
SYMBOL_BOT_MAP="{\"BINANCE:SOLUSDT\":\"9d9a27de-0a9a-4356-a68e-67a988856dac\"}"

ENABLE_HTTP_FORWARD="true"
C3_SIGNAL_URL="https://api.3commas.io/signal_bots/webhooks"
C3_SIGNAL_SECRET="YOUR_3COMMAS_SIGNAL_SECRET"
C3_TIMEOUT_MS="8000"
MAX_LAG_SEC="300"

ENTRY_MODE="SCORE_ENGINE_V2"

PRIMARY_FEATURE_TF="3"
FALLBACK_FEATURE_TF="5"
PRIMARY_FEATURE_MAX_AGE_SEC="240"
FALLBACK_FEATURE_MAX_AGE_SEC="420"

ALLOW_TREND_CHANGE_ENTRY="true"
ALLOW_BOS_ENTRY="true"
ALLOW_TREND_CONTINUATION_ENTRY="false"

TREND_CHANGE_MIN_SCORE="5"
BOS_MIN_SCORE="6"
PENDING_MIN_SCORE="4"
PENDING_TREND_CHANGE_ENTRY="true"
PENDING_TREND_CHANGE_TTL_MIN="12"

SCORE_MEMORY_ENABLED="true"
SCORE_MEMORY_TTL_MIN="10"
SCORE_MEMORY_MIN_SCORE="5"

HARD_BLOCKS_ENABLED="true"
CHASE_PUMP_LOOKBACK_BARS="3"
CHASE_PUMP_BLOCK_PCT="1.20"
CHASE_EXT_EMA11_BLOCK_PCT="0.70"
CHASE_RSI_BLOCK="72"

RECENT_BEARISH_BLOCK_MIN="10"

LOCK_AFTER_ENTER="true"
ENTRY_COOLDOWN_SEC="300"
ENTER_DEDUP_SEC="25"

EXIT_ON_BEARISH_TREND_CHANGE="true"
EXIT_ON_BEARISH_BOS="true"
EXIT_ON_BEARISH_TREND_CONTINUATION="false"

EXIT_DEDUP_SEC="20"
EXIT_COOLDOWN_SEC="60"

REQUIRE_KNOWN_SIGNAL="true"
