const num = (v, d) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : d;
};

const bool = (v, d = false) => {
  if (v === undefined || v === null || v === "") return d;
  return String(v).trim().toLowerCase() === "true";
};

export const CONFIG = {
  BRAIN_VERSION: process.env.BRAIN_VERSION || "Brain Phase 5 v5.5",
  SYMBOL: process.env.SYMBOL || "BINANCE:SOLUSDT",
  TF: process.env.TF || "3",

  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET || "",
  PORT: num(process.env.PORT, 8080),

  // Regime
  REGIME_ADX_TREND_MIN: num(process.env.REGIME_ADX_TREND_MIN, 20),
  REGIME_ADX_RANGE_MAX: num(process.env.REGIME_ADX_RANGE_MAX, 14),
  REGIME_ATRPCT_MIN: num(process.env.REGIME_ATRPCT_MIN, 0.18),

  // Breakout lifecycle
  BREAKOUT_ENABLED: bool(process.env.BREAKOUT_ENABLED, true),
  BREAKOUT_MIN_SCORE: num(process.env.BREAKOUT_MIN_SCORE, 7),
  BREAKOUT_MIN_IMPULSE_PCT: num(process.env.BREAKOUT_MIN_IMPULSE_PCT, 0.18),
  BREAKOUT_RETEST_TOLERANCE_PCT: num(process.env.BREAKOUT_RETEST_TOLERANCE_PCT, 0.15),
  BREAKOUT_CONFIRM_BOUNCE_PCT: num(process.env.BREAKOUT_CONFIRM_BOUNCE_PCT, 0.08),
  BREAKOUT_MAX_RETEST_BARS: num(process.env.BREAKOUT_MAX_RETEST_BARS, 4),
  BREAKOUT_SETUP_EXPIRY_BARS: num(process.env.BREAKOUT_SETUP_EXPIRY_BARS, 6),

  // Breakout hardening
  BREAKOUT_READY_EXPIRY_BARS: num(process.env.BREAKOUT_READY_EXPIRY_BARS, 3),
  BREAKOUT_MIN_PULLBACK_PCT: num(process.env.BREAKOUT_MIN_PULLBACK_PCT, 0.10),
  BREAKOUT_RETEST_LOW_BUFFER_PCT: num(process.env.BREAKOUT_RETEST_LOW_BUFFER_PCT, 0.05),
  BREAKOUT_REQUIRE_CLOSE_BACK_ABOVE_TRIGGER: bool(
    process.env.BREAKOUT_REQUIRE_CLOSE_BACK_ABOVE_TRIGGER,
    true
  ),
  MAX_CLOSE_BELOW_TRIGGER_TOLERANCE_PCT: num(
    process.env.MAX_CLOSE_BELOW_TRIGGER_TOLERANCE_PCT,
    0.10
  ),

  BREAKOUT_REQUIRE_EMA8_ABOVE_EMA18_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_EMA8_ABOVE_EMA18_ON_ENTRY,
    true
  ),
  BREAKOUT_REQUIRE_RSI_MIN_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_RSI_MIN_ON_ENTRY,
    false
  ),
  BREAKOUT_RSI_MIN_ON_ENTRY: num(process.env.BREAKOUT_RSI_MIN_ON_ENTRY, 50),
  BREAKOUT_MAX_READY_AGE_BARS_FOR_ENTRY: num(
    process.env.BREAKOUT_MAX_READY_AGE_BARS_FOR_ENTRY,
    2
  ),

  // Validation / extension
  MAX_ENTRY_EXTENSION_FROM_EMA18_PCT: num(
    process.env.MAX_ENTRY_EXTENSION_FROM_EMA18_PCT,
    0.70
  ),
  MAX_ENTRY_EXTENSION_FROM_TRIGGER_PCT: num(
    process.env.MAX_ENTRY_EXTENSION_FROM_TRIGGER_PCT,
    0.35
  ),
  ALLOW_ENTRY_ON_BOUNCE_CONFIRMED: bool(
    process.env.ALLOW_ENTRY_ON_BOUNCE_CONFIRMED,
    true
  ),
  BREAKOUT_MAX_SOFT_REASONS: num(process.env.BREAKOUT_MAX_SOFT_REASONS, 2),

  // Entry quality
  BREAKOUT_REQUIRE_MEANINGFUL_PULLBACK_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_MEANINGFUL_PULLBACK_ON_ENTRY,
    true
  ),
  BREAKOUT_REQUIRE_RETEST_NEAR_EMA8_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_RETEST_NEAR_EMA8_ON_ENTRY,
    true
  ),
  BREAKOUT_REQUIRE_HELD_ABOVE_EMA18_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_HELD_ABOVE_EMA18_ON_ENTRY,
    true
  ),

  BREAKOUT_REQUIRE_BOUNCE_PCT_MIN_ON_BOUNCE_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_BOUNCE_PCT_MIN_ON_BOUNCE_ENTRY,
    true
  ),
  BREAKOUT_MIN_BOUNCE_PCT_FOR_ENTRY: num(
    process.env.BREAKOUT_MIN_BOUNCE_PCT_FOR_ENTRY,
    0.05
  ),

  BREAKOUT_REQUIRE_BOUNCE_BODY_MIN_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_BOUNCE_BODY_MIN_ON_ENTRY,
    true
  ),
  BREAKOUT_REQUIRE_CLOSE_IN_RANGE_MIN_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_CLOSE_IN_RANGE_MIN_ON_ENTRY,
    true
  ),
  BREAKOUT_REQUIRE_RECLAIM_ABOVE_TRIGGER_MIN_ON_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_RECLAIM_ABOVE_TRIGGER_MIN_ON_ENTRY,
    true
  ),

  BREAKOUT_MIN_BOUNCE_BODY_PCT: num(process.env.BREAKOUT_MIN_BOUNCE_BODY_PCT, 0.08),
  BREAKOUT_MIN_CLOSE_IN_RANGE_PCT: num(process.env.BREAKOUT_MIN_CLOSE_IN_RANGE_PCT, 55),
  BREAKOUT_MIN_RECLAIM_ABOVE_TRIGGER_PCT: num(
    process.env.BREAKOUT_MIN_RECLAIM_ABOVE_TRIGGER_PCT,
    0.03
  ),

  BREAKOUT_REQUIRE_STRONG_OI_ON_BOUNCE_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_STRONG_OI_ON_BOUNCE_ENTRY,
    false
  ),
  BREAKOUT_REQUIRE_STRONG_CVD_ON_BOUNCE_ENTRY: bool(
    process.env.BREAKOUT_REQUIRE_STRONG_CVD_ON_BOUNCE_ENTRY,
    false
  ),
  BREAKOUT_BLOCK_IF_FLOW_NOT_SUPPORTIVE: bool(
    process.env.BREAKOUT_BLOCK_IF_FLOW_NOT_SUPPORTIVE,
    false
  ),

  BREAKOUT_MAX_CHASE_FROM_BOUNCE_PCT_BOUNCE_ENTRY: num(
    process.env.BREAKOUT_MAX_CHASE_FROM_BOUNCE_PCT_BOUNCE_ENTRY,
    0.20
  ),
  BREAKOUT_MAX_CHASE_FROM_BOUNCE_PCT_READY_ENTRY: num(
    process.env.BREAKOUT_MAX_CHASE_FROM_BOUNCE_PCT_READY_ENTRY,
    0.35
  ),
  BREAKOUT_MAX_CHASE_FROM_TRIGGER_PCT_CONTINUATION_ENTRY: num(
    process.env.BREAKOUT_MAX_CHASE_FROM_TRIGGER_PCT_CONTINUATION_ENTRY,
    0.28
  ),

  // Continuation mode
  BREAKOUT_CONTINUATION_ADX_MIN: num(
    process.env.BREAKOUT_CONTINUATION_ADX_MIN,
    22
  ),
  BREAKOUT_CONTINUATION_RSI_MIN: num(
    process.env.BREAKOUT_CONTINUATION_RSI_MIN,
    58
  ),
  BREAKOUT_CONTINUATION_MIN_EXTENSION_PCT: num(
    process.env.BREAKOUT_CONTINUATION_MIN_EXTENSION_PCT,
    0.12
  ),
  BREAKOUT_CONTINUATION_MIN_BARS: num(
    process.env.BREAKOUT_CONTINUATION_MIN_BARS,
    1
  ),

  BREAKOUT_ALLOW_ONE_REENTRY_AFTER_FAST_FAILURE: bool(
    process.env.BREAKOUT_ALLOW_ONE_REENTRY_AFTER_FAST_FAILURE,
    false
  ),
  BREAKOUT_REENTRY_ALLOWED_EXIT_REASON:
    process.env.BREAKOUT_REENTRY_ALLOWED_EXIT_REASON || "close_below_ema18",

  // Setup engine specific
  BREAKOUT_SETUP_ADX_MIN: num(process.env.BREAKOUT_SETUP_ADX_MIN, 20),
  BREAKOUT_SHALLOW_PULLBACK_PCT: num(process.env.BREAKOUT_SHALLOW_PULLBACK_PCT, 0.08),
  BREAKOUT_RETEST_NEAR_TRIGGER_PCT: num(process.env.BREAKOUT_RETEST_NEAR_TRIGGER_PCT, 0.12),
  BREAKOUT_SHALLOW_RETEST_MIN_ADX: num(process.env.BREAKOUT_SHALLOW_RETEST_MIN_ADX, 22),
  BREAKOUT_MIN_READY_BOUNCE_PCT: num(process.env.BREAKOUT_MIN_READY_BOUNCE_PCT, 0.06),

  // Execution mode
  EXECUTION_MODE: process.env.EXECUTION_MODE || "dry_run",
  DRY_RUN_EXECUTION_ENABLED: bool(process.env.DRY_RUN_EXECUTION_ENABLED, true),

  // Replay
  REPLAY_SIGNAL_MODE: bool(process.env.REPLAY_SIGNAL_MODE, false),
  REPLAY_MAX_LAG_SEC: num(process.env.REPLAY_MAX_LAG_SEC, 3600),

  // Live guardrails
  LIVE_EXECUTION_ENABLED: bool(process.env.LIVE_EXECUTION_ENABLED, false),
  LIVE_MANUAL_ARMING_ENABLED: bool(process.env.LIVE_MANUAL_ARMING_ENABLED, false),
  ALLOW_ONLY_ONE_ENTRY_PER_SETUP: bool(
    process.env.ALLOW_ONLY_ONE_ENTRY_PER_SETUP,
    true
  ),
  ENTRY_COOLDOWN_BARS: num(process.env.ENTRY_COOLDOWN_BARS, 3),

  // 3Commas
  C3_WEBHOOK_URL:
    process.env.C3_WEBHOOK_URL ||
    "https://api.3commas.io/signal_bots/webhooks",
  C3_SIGNAL_SECRET: process.env.C3_SIGNAL_SECRET || "",
  C3_BOT_UUID: process.env.C3_BOT_UUID || "",
  C3_MAX_LAG_SEC: num(process.env.C3_MAX_LAG_SEC, 300),

  // Position size
  C3_ENTRY_AMOUNT: process.env.C3_ENTRY_AMOUNT || "199",
  C3_ENTRY_CURRENCY_TYPE: process.env.C3_ENTRY_CURRENCY_TYPE || "quote",
  C3_RISK_MODE: process.env.C3_RISK_MODE || "fixed",

  // Dynamic risk sizing
  ACCOUNT_EQUITY: num(process.env.ACCOUNT_EQUITY, 1000),
  RISK_PER_TRADE_PCT: num(process.env.RISK_PER_TRADE_PCT, 1.0),
  MIN_POSITION_QUOTE: num(process.env.MIN_POSITION_QUOTE, 25),
  MAX_POSITION_QUOTE: num(process.env.MAX_POSITION_QUOTE, 250),

  // Position management
  INIT_STOP_ATR_MULT: num(process.env.INIT_STOP_ATR_MULT, 1.8),
  INIT_STOP_EMA_BUFFER_ATR_MULT: num(process.env.INIT_STOP_EMA_BUFFER_ATR_MULT, 0.3),
  BREAKEVEN_ARM_PCT: num(process.env.BREAKEVEN_ARM_PCT, 0.35),
  TRAILING_START_PCT: num(process.env.TRAILING_START_PCT, 0.55),
  TRAILING_ATR_MULT: num(process.env.TRAILING_ATR_MULT, 1.4),
  PROFIT_LOCK_ARM_PCT: num(process.env.PROFIT_LOCK_ARM_PCT, 0.9),
  PROFIT_LOCK_GIVEBACK_PCT: num(process.env.PROFIT_LOCK_GIVEBACK_PCT, 0.35),
  EXIT_ON_CLOSE_BELOW_EMA18: bool(process.env.EXIT_ON_CLOSE_BELOW_EMA18, true),

  // Debug
  LOG_FULL_STATE_ON_TRANSITIONS: bool(
    process.env.LOG_FULL_STATE_ON_TRANSITIONS,
    true
  ),
  LOG_SIGNAL_PAYLOADS: bool(process.env.LOG_SIGNAL_PAYLOADS, true),
};
