export const CONFIG = {
  BRAIN_VERSION: "Brain Phase 5 v5.0",
  SYMBOL: "BINANCE:SOLUSDT",
  TF: "3",

  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET || "",
  PORT: Number(process.env.PORT || 8080),

  // Regime
  REGIME_ADX_TREND_MIN: 20,
  REGIME_ADX_RANGE_MAX: 14,
  REGIME_ATRPCT_MIN: 0.18,

  // Breakout lifecycle
  BREAKOUT_ENABLED: true,
  BREAKOUT_MIN_SCORE: 7,
  BREAKOUT_MIN_IMPULSE_PCT: 0.18,
  BREAKOUT_RETEST_TOLERANCE_PCT: 0.15,
  BREAKOUT_CONFIRM_BOUNCE_PCT: 0.08,
  BREAKOUT_MAX_RETEST_BARS: 4,
  BREAKOUT_SETUP_EXPIRY_BARS: 6,

  // Validation
  MAX_ENTRY_EXTENSION_FROM_EMA18_PCT: 0.70,
  MAX_ENTRY_EXTENSION_FROM_TRIGGER_PCT: 0.35,
  ALLOW_ENTRY_ON_BOUNCE_CONFIRMED: true,

  // Execution
  EXECUTION_MODE: process.env.EXECUTION_MODE || "dry_run", // dry_run | live
  DRY_RUN_EXECUTION_ENABLED: true,
  LIVE_EXECUTION_ENABLED: process.env.LIVE_EXECUTION_ENABLED === "true",
  ALLOW_ONLY_ONE_ENTRY_PER_SETUP: true,
  ENTRY_COOLDOWN_BARS: 3,

  // 3Commas / Signal Bot
  C3_WEBHOOK_URL:
    process.env.C3_WEBHOOK_URL ||
    "https://api.3commas.io/signal_bots/webhooks",
  C3_SIGNAL_SECRET: process.env.C3_SIGNAL_SECRET || "",
  C3_BOT_UUID: process.env.C3_BOT_UUID || "",
  C3_MAX_LAG_SEC: Number(process.env.C3_MAX_LAG_SEC || 300),

  // Debug
  LOG_FULL_STATE_ON_TRANSITIONS: true,
};
